### ISSUE TITLE
ConcurrentModificationException on post decorators in BuildRefData

### ISSUE THREAD

**Issue by kennethjor** [autonomouslogic/eve-ref#269]
When the post decorators run in `BuildRefData` on AWS, a `ConcurrentModificationException` happens regularly:

```
2023-09-14T21:05:36,791 [INFO] (RxComputationThreadPool-2) MutaplasmidDecorator: Decorating mutaplasmids
2023-09-14T21:05:37,350 [INFO] (RxComputationThreadPool-2) VariationsDecorator: Populates variations
2023-09-14T21:05:42,585 [FATAL] (main) Main: Root error, exiting
org.h2.mvstore.MVStoreException: This store is closed [2.1.214/4]
        at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.checkOpen(MVStore.java:3087) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.getChunk(MVStore.java:1381) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2566) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVMap.readPage(MVMap.java:633) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1125) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.CursorPos.traverseDown(CursorPos.java:61) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVMap.operate(MVMap.java:1770) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVMap.put(MVMap.java:156) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at com.autonomouslogic.everef.cli.refdata.post.VariationsDecorator.populateTypeVariations(VariationsDecorator.java:124) ~[eve-ref-2.27.0.jar:?]
        at com.autonomouslogic.everef.cli.refdata.post.VariationsDecorator.lambda$populateVariations$3(VariationsDecorator.java:112) ~[eve-ref-2.27.0.jar:?]
        at java.util.TreeMap.forEach(Unknown Source) ~[?:?]
        at com.autonomouslogic.everef.cli.refdata.post.VariationsDecorator.lambda$populateVariations$4(VariationsDecorator.java:110) ~[eve-ref-2.27.0.jar:?]
        at java.util.HashMap.forEach(Unknown Source) ~[?:?]
        at com.autonomouslogic.everef.cli.refdata.post.VariationsDecorator.populateVariations(VariationsDecorator.java:107) ~[eve-ref-2.27.0.jar:?]
        at com.autonomouslogic.everef.cli.refdata.post.VariationsDecorator.lambda$create$0(VariationsDecorator.java:53) ~[eve-ref-2.27.0.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:36) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onComplete(CompletableConcatArray.java:65) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableMergeArray$InnerCompletableObserver.onComplete(CompletableMergeArray.java:90) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:154) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onComplete(FlowableFlatMapCompletableCompletable.java:157) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.innerComplete(FlowableFlatMapCompletableCompletable.java:180) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber$InnerObserver.onComplete(FlowableFlatMapCompletableCompletable.java:198) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:154) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onComplete(FlowableFlatMapCompletableCompletable.java:157) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:204) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:129) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onSubscribe(FlowableFlatMapCompletableCompletable.java:105) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable.subscribeActual(FlowableFlatMapCompletableCompletable.java:56) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-3.1.6.jar:?]
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25) ~[rxjava-3.1.6.jar:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: org.h2.mvstore.MVStoreException: com.fasterxml.jackson.databind.JsonMappingException: [no message for java.util.ConcurrentModificationException] [2.1.214/3]
        at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.serializeAndStore(MVStore.java:1605) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.lambda$storeNow$4(MVStore.java:1518) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        ... 3 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: [no message for java.util.ConcurrentModificationException]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._wrapAsIOE(DefaultSerializerProvider.java:508) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:481) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3987) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.autonomouslogic.everef.mvstore.JsonNodeDataType.write(JsonNodeDataType.java:22) ~[eve-ref-2.27.0.jar:?]
        at org.h2.mvstore.type.BasicDataType.write(BasicDataType.java:67) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$Leaf.writeValues(Page.java:1609) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page.write(Page.java:721) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$Leaf.writeUnsavedRecursive(Page.java:1618) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.serializeToBuffer(MVStore.java:1669) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.serializeAndStore(MVStore.java:1598) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.lambda$storeNow$4(MVStore.java:1518) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        ... 3 more
Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:?]
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:?]
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:?]
        at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:433) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:39) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:20) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3987) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.autonomouslogic.everef.mvstore.JsonNodeDataType.write(JsonNodeDataType.java:22) ~[eve-ref-2.27.0.jar:?]
        at org.h2.mvstore.type.BasicDataType.write(BasicDataType.java:67) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$Leaf.writeValues(Page.java:1609) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page.write(Page.java:721) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$Leaf.writeUnsavedRecursive(Page.java:1618) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeChildrenRecursive(Page.java:1344) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.Page$NonLeaf.writeUnsavedRecursive(Page.java:1330) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.serializeToBuffer(MVStore.java:1669) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.serializeAndStore(MVStore.java:1598) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.lambda$storeNow$4(MVStore.java:1518) ~[h2-mvstore-2.1.214.jar:2.1.214]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        ... 3 more
```

While this particular instance happens in `VariationsDecorator`, I've checked some other runs where it happens in `BlueprintDecorator`, so it's not related to a specific decorator.

However, in both cases the error happens when trying to save a type to MVStore, which would indicate that something is trying to alter the type in question while it's being saved.

**Comment by kennethjor** [comment]
The issue seems to be that MVStore keeps the object around for async serialisation. This causes subsequent edits to throw the exception, because the object is being modified during serialisation. I've opened a ticket with h2data: https://github.com/h2database/h2database/issues/3898

The immediate solution could be to use a `byte[]` data type instead and serialise immediately on every save.
