### ISSUE TITLE
Build Ref Data failed with NullPointerException

### ISSUE THREAD

**Issue by kennethjor** [autonomouslogic/eve-ref#592]
Build Ref Data has been failing since 2024-09-18T12:12:19 with a NullPointerException:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.autonomouslogic.everef.refdata.InventoryType.getTypeId()" is null
    at com.autonomouslogic.everef.cli.refdata.post.VariationsDecorator.resolveDynamicVariations(VariationsDecorator.java:83)
    at com.autonomouslogic.everef.cli.refdata.post.VariationsDecorator.lambda$create$0(VariationsDecorator.java:45)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:36)
    at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
    at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43)
    at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatIterable$ConcatInnerObserver.next(CompletableConcatIterable.java:119)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatIterable.subscribeActual(CompletableConcatIterable.java:47)
    at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onComplete(CompletableConcatArray.java:65)
    at io.reactivex.rxjava3.internal.operators.completable.CompletableMergeArray$InnerCompletableObserver.onComplete(CompletableMergeArray.java:90)
    at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:154)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onComplete(FlowableFlatMapCompletableCompletable.java:157)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:217)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:395)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:178)
    at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:80)
    at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:71)
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
```

**Comment by kennethjor** [comment]
Looks like this is caused by types being loaded in from Hoboleaks which aren't in the SDE or ESI scrape. A new SDE was just released and the ESI scrape has been down.

**Comment by kennethjor** [comment]
New SDE was published, which fixed the issue as expected. ESI has now been scraped as well. So all good :+1:
